
import { VisaFormData } from '../types';

export interface VisaExportMeta {
  generatedAt: string;
  appName: string;
  isDraft: boolean;
}

export type VisaExportData = VisaFormData & { meta: VisaExportMeta };

/**
 * Prepares the data object with metadata.
 */
export const prepareExportData = (formData: VisaFormData): VisaExportData => {
  return {
    ...formData,
    meta: {
      generatedAt: new Date().toISOString(),
      appName: "Omnitrip",
      isDraft: true
    }
  };
};

/**
 * Triggers a browser download for a JSON file.
 */
export const downloadJSON = (data: VisaExportData, filename: string) => {
  const jsonStr = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Copies a formatted text summary to clipboard.
 */
export const copyToClipboard = async (data: VisaExportData): Promise<boolean> => {
  const text = `
VISA APPLICATION DRAFT (OMNITRIP)
=================================
Generated: ${new Date(data.meta.generatedAt).toLocaleString()}

-- APPLICANT --
Name: ${data.fullName}
Passport: ${data.passportNumber}
Nationality: ${data.nationality}
DOB: ${data.dateOfBirth}

-- TRIP --
Dates: ${data.tripStartDate} to ${data.tripEndDate}
Purpose: ${data.purpose}
Address: ${data.accommodationAddress}

=================================
* Draft only. Verify against official requirements.
  `;
  
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (e) {
    console.error("Clipboard failed", e);
    return false;
  }
};

/**
 * Opens a new window with a print-optimized HTML layout.
 * Relies on the browser's native "Print to PDF" capability.
 */
export const printVisaDraft = (data: VisaExportData) => {
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Visa Draft - ${data.fullName}</title>
        <style>
          body { 
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; 
            padding: 40px; 
            max-width: 800px; 
            margin: 0 auto; 
            color: #333;
            line-height: 1.5;
          }
          .header { 
            border-bottom: 3px solid #333; 
            padding-bottom: 20px; 
            margin-bottom: 30px; 
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
          }
          h1 { margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 1px; }
          .sub-header { font-size: 12px; color: #666; }
          
          .section { margin-bottom: 30px; }
          .section-title { 
            font-size: 14px; 
            font-weight: bold; 
            text-transform: uppercase; 
            color: #666; 
            border-bottom: 1px solid #eee; 
            padding-bottom: 5px; 
            margin-bottom: 15px;
          }
          
          .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
          .field { margin-bottom: 15px; }
          .label { font-size: 10px; text-transform: uppercase; font-weight: bold; color: #888; margin-bottom: 4px; }
          .value { 
            font-size: 16px; 
            font-weight: 500; 
            border-bottom: 1px dashed #ccc; 
            padding-bottom: 4px; 
            min-height: 24px;
          }
          
          .footer { 
            margin-top: 60px; 
            border-top: 1px solid #eee; 
            padding-top: 20px; 
            font-size: 10px; 
            color: #999; 
            text-align: center;
          }
          
          @media print { 
            body { padding: 0; } 
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Visa Application Draft</h1>
            <div class="sub-header">Generated by Omnitrip • Draft ID: ${Date.now().toString().slice(-6)}</div>
          </div>
          <div style="text-align: right">
            <div style="font-size: 32px;">✈️</div>
          </div>
        </div>
        
        <div class="section">
          <div class="section-title">Applicant Information</div>
          <div class="grid">
            <div class="field">
              <div class="label">Full Name</div>
              <div class="value">${data.fullName || ''}</div>
            </div>
            <div class="field">
              <div class="label">Nationality</div>
              <div class="value">${data.nationality || ''}</div>
            </div>
            <div class="field">
              <div class="label">Passport Number</div>
              <div class="value">${data.passportNumber || ''}</div>
            </div>
            <div class="field">
              <div class="label">Date of Birth</div>
              <div class="value">${data.dateOfBirth || ''}</div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Trip Details</div>
          <div class="grid">
            <div class="field">
              <div class="label">Start Date</div>
              <div class="value">${data.tripStartDate || ''}</div>
            </div>
            <div class="field">
              <div class="label">End Date</div>
              <div class="value">${data.tripEndDate || ''}</div>
            </div>
            <div class="field" style="grid-column: span 2;">
              <div class="label">Main Accommodation Address</div>
              <div class="value">${data.accommodationAddress || ''}</div>
            </div>
            <div class="field" style="grid-column: span 2;">
              <div class="label">Purpose of Travel</div>
              <div class="value">${data.purpose || ''}</div>
            </div>
          </div>
        </div>

        <div class="footer">
          * This document is a draft generated for planning purposes. It is not an official government document.<br/>
          Please verify all details against official requirements before submission.
        </div>
        
        <script>
          setTimeout(() => {
            window.print();
          }, 500);
        </script>
      </body>
    </html>
  `;
  
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
  } else {
    alert("Popup blocked! Please allow popups to print.");
  }
};
